export const LOAD_NEWS = "LOAD_NEWS";
export const SEARCH_NEWS = "SEARCH_NEWS";

export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const ADD_BOOKMARK_SUCCESS = "ADD_BOOKMARK_SUCCESS";
export const ADD_BOOKMARK_FAIL = "ADD_BOOKMARK_FAIL";
export const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";
export const LOADED_BOOKMARKS = "LOADED_BOOKMARKS";
export const VIEW_BOOKMARKS = 'VIEW_BOOKMARKS';

export const LOAD_PROFILE_IMAGE = "LOAD_PROFILE_IMAGE"
export const SAVE_PROFILE_IMAGE = "SAVE_PROFILE_IMAGE"
