export const LOAD_NEWS = "LOAD_NEWS";
export const SEARCH_NEWS = "SEARCH_NEWS";
export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const ADD_BOOKMARK_SUCCESS = "ADD_BOOKMARK_SUCCESS";
export const ADD_BOOKMARK_FAIL = "ADD_BOOKMARK_FAIL";
export const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";
export const LOADED_BOOKMARKS = "LOADED_BOOKMARKS";
